{% set name = "satchip" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/satchip-{{ version }}.tar.gz
  sha256: 3d60ddfe50d5cf8ec993642e3fbf4ff76c9034729b220971568fa4024107b0a9

build:
  entry_points:
    - chiplabel = satchip.chip_label:main
    - chipdata = satchip.chip_data:main
    - chipview = satchip.chip_view:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - numpy
    - shapely
    - pyproj
    - pystac-client
    - rasterio
    - zarr >=3
    - xarray
    - rioxarray
    - pandas
    - geopandas
    - asf_search
    - earthaccess
    - hyp3_sdk
    - tqdm
    - matplotlib-base

test:
  imports:
    - satchip
  commands:
    - pip check
    - chiplabel --help
    - chipdata --help
    - chipview --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A package for satellite image AI data prep
  home: https://github.com/forrestfwilliams/satchip
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forrestfwilliams
